export type BlogPost = {
  slug: string;
  title: string;
  excerpt: string;
  date: string; // ISO
  content: string[]; // paragraphs
};

export const BLOG_POSTS: BlogPost[] = [
  {
    slug: "five-ways-to-use-practice-worksheets-effectively",
    title: "5 Ways to Use Practice Worksheets Effectively",
    excerpt: "Worksheets work best as part of a routine, not a one-off. Here's how to get real results from them.",
    date: "2026-06-01",
    content: [
      "Worksheets get a bad reputation as busywork — but used well, they're one of the fastest ways to build fluency in a specific skill. The difference between \"busywork\" and \"effective practice\" usually comes down to how they're used, not the worksheet itself.",
      "1. Keep sessions short and frequent. Ten focused minutes a day on one topic beats a single hour-long cram session. Short, low-pressure repetition is what actually builds fluency.",
      "2. Match difficulty to where the student actually is, not where they \"should\" be. If a worksheet feels too easy or too hard, it stops being useful — dial the difficulty up or down rather than pushing through frustration or boredom.",
      "3. Always review the answer key together, right after. The value of practice comes from correcting mistakes while the reasoning is still fresh, not days later.",
      "4. Rotate topics instead of drilling one skill to exhaustion. A little variety (a few fraction problems, a couple of word problems, a quick vocabulary review) keeps a session from feeling like a grind.",
      "5. Track progress loosely, not obsessively. A simple \"we did 4 worksheets this week\" is often more motivating for a student than a detailed score log — celebrate consistency over perfection.",
    ],
  },
  {
    slug: "how-we-keep-every-answer-key-accurate",
    title: "How We Keep Every Answer Key Accurate",
    excerpt: "Why we don't let an AI model guess at math answers — and what we do instead.",
    date: "2026-06-10",
    content: [
      "A worksheet is only useful if its answer key is right. That sounds obvious, but a lot of auto-generated content online gets this wrong — especially anything produced by asking a general-purpose AI model to \"write some math problems,\" since language models can be confidently wrong about arithmetic.",
      "For math, every question on Practice Sheet is generated by actual code that computes the answer the same way a calculator would — the numbers are randomized, but the arithmetic itself is never guessed. If a worksheet asks for 347 × 12, the answer key wasn't predicted by a model; it was calculated.",
      "For English and Science, where questions are about facts and rules rather than calculations, we use curated, human-reviewed question banks instead of open-ended generation — so a grammar rule or a science fact on the page is one we've actually verified, not one that sounded plausible.",
      "This is slower to build than just prompting an AI model for endless content, but it's the only way we're comfortable putting our name on an answer key.",
    ],
  },
  {
    slug: "grade-by-grade-guide-to-math-topics",
    title: "A Grade-by-Grade Guide to Math Topics",
    excerpt: "What's typically taught when — a quick reference for parents helping at home.",
    date: "2026-06-18",
    content: [
      "Curricula vary by school and region, but there's a fairly consistent general progression most students follow. Here's a rough guide if you're not sure what to focus practice on.",
      "Grades 1–2: counting, addition and subtraction within 100, basic shapes, comparing numbers.",
      "Grades 3–4: multiplication and division facts, introduction to fractions and decimals, place value, simple word problems.",
      "Grades 5–6: fraction and decimal operations, ratios, percentages, negative numbers, early algebraic expressions.",
      "Grades 7–8: proportional relationships, linear equations, the Pythagorean theorem, introductory geometry and statistics.",
      "Grades 9–10: Algebra I and Geometry — factoring, quadratic equations, coordinate geometry, formal proofs.",
      "Grades 11–12: Algebra II and Precalculus — logarithms, sequences and series, trigonometric ratios, and early functions/limits work.",
      "If a student is consistently struggling with a topic, it's often worth stepping back one grade level of practice rather than pushing forward — fluency with the basics makes everything after it faster.",
    ],
  },
];

export function getPostBySlug(slug: string): BlogPost | undefined {
  return BLOG_POSTS.find((p) => p.slug === slug);
}
